### ISSUE TITLE
Is ml-pipeline-X is also doing `git commit/push` or only `dvc push`

### ISSUE THREAD

**Issue by PuneethaPai** [ThoughtWorksInc/continuous-intelligence-workshop#3]
Instructions [3-machine-learning-pipeline.](https://github.com/ThoughtWorksInc/cd4ml-workshop/blob/master/instructions/3-machine-learning-pipeline.md)

Asks us to 
- run dvc pipelines in local
- git commit and push
- define pipeline from a template

## Want to understand can you clearly tell what all stages/tasks/job this `ml-pipeline-X` is running?
- My guess is it just runs dvc repro and dvc push
- Also do you use docker containers to train the model or on the bare worker?

If you can define you pipeline stages in yml files and share that would be great.

**Comment by dtsato** [comment]
GoCD supports pipeline as code, where you can define them either in JSON or YAML. You can check the documentation [here](https://docs.gocd.org/current/advanced_usage/pipelines_as_code.html).

Also, the newer versions of DVC also support defining the DVC steps in a [dvc.yaml](https://docs.gocd.org/current/advanced_usage/pipelines_as_code.html) file.
