### ISSUE TITLE
https://jupyterhub.cd4ml.net is not accessible.

### ISSUE THREAD

**Issue by rajanmanwansh** [ThoughtWorksInc/continuous-intelligence-workshop#4]
Trying to follow the steps mentioned in cd4ml-workshop/instructions/1-setup.md

Step3:Go to Jupyter Lab at https://jupyterhub.cd4ml.net and login with the username and password provided.

Getting site can't be reached.

Please help.

**Comment by lucasarea90** [comment]
Same error here

**Comment by riachandran** [comment]
Same here

**Comment by dtsato** [comment]
We only provision the supporting infrastructure when running the workshop, it is unfortunately not available on demand. We are working to open source the repository with the infrastructure code, so you can replicate the environment (with modifications) on your own GCP account. Closing for now.
